### ISSUE TITLE
N'utilisez les norloges iso que si le jour du post cité est différent du post courant

### ISSUE THREAD

**Issue by claudex** [devnewton/jb3#16]
Les norloges ISO font juste chier tout le monde sans apporter aucune fonctionnalité.

**Comment by devnewton** [comment]
La date dans les norloges permets:

- de répondre à un POST sans ambiguïté sur la date.
- d'éviter de devoir remonter dans le backend jour par jour en s'arrêtant au premier POST avec le même trio heure/minute/seconde (algorithme _norloge look behind highlight_).

On pourrait désactiver la date uniquement dans un cas: celui  la norloge trouvé par _norloge look behind highlight_ est à la même date que le POST.

Dans tous les cas (référence à un POST d'hier ou plus, IPOT), la date est nécessaire.

**Comment by claudex** [comment]
>On pourrait désactiver la date uniquement dans un cas: celui la norloge trouvé par norloge look behind highlight est à la même date que le POST.

Comme le font tous les coincoin, c'est beaucoup plus lisible. D'ail

**Comment by claudex** [comment]
leurs, la date n'est nécessaire que si le post auquel on répond à plus de 24h (désolé pour le double post, mobile à la con).

**Comment by n-e** [comment]
Cette fonctionnalité est incompatible avec les nombreux outils legacy qui ne seront probablement jamais mis à jour pour la supporter (tribune web linuxfr, faab, wmcoincoin, etc.). Cette raison à elle seule devrait être suffisante pour la désactiver.

De plus, les avantages supposés sont inexistants : 

> de répondre à un POST sans ambiguïté sur la date.

Les posts ayant la même horloge à la seconde près mais datant de jours différents sont rares, et par ailleurs il existe déjà le format "DD/MM#horloge" qui est plus compact et évite de polluer les horloges concernant le jour même, qui concernent la grande majorité des posts.

> d'éviter de devoir remonter dans le backend jour par jour en s'arrêtant au premier POST avec le même trio heure/minute/seconde (algorithme norloge look behind highlight).

Cette algorithme n'est jamais nécessaire, il suffit d'utiliser un index pour qu'une requête naïve s'exécute en O(log n) -- par exemple sur bombefourchette.com les requêtes sont instantanées alors que des millions de posts sont indexés.

Par ailleurs, il ne faut pas oublier qu'on parle d'un logiciel de chat. Il n'est pas nécessaire d'identifier de façon exacte le post concerné, et dans le cas où il y a une ambiguité une simple lecture des posts la résoudra.

**Comment by devnewton** [comment]
Il me semble que le format DD/MM#horloge est spécifique à olcc. De plus, il est moins que le format iso, donc il n'est pas pertinent dans ce contexte.

Concernant l'esthétique de ces norloges, cela concerne uniquement l'affichage. Les coincoins vivants du marché reformatent toujours le BML en général et les norloges iso en particulier depuis les dernières mises à jour de quteqoin, jb3, taab et olcc.

Concernant les coincoins legacy, je comprends la préoccupation de leurs 3 ou 4 utilisateurs. Toutefois la déisofication de certaines norloges ne règlera pas le présumé problème esthétique dans son ensemble.

Je n'ai pas compris la remarque sur l'index.

Quand à la résolution visuelle des ambigüités de post, elle est toujours possible, mais non souhaitable.

**Comment by devnewton** [comment]
Qu'est-ce qui empêche de patcher faab, dlfp et wmcc aujourd'hui?

**Comment by claudex** [comment]
>Il me semble que le format DD/MM#horloge est spécifique à olcc.

Et quteqoin

>Toutefois la déisofication de certaines norloges ne règlera pas le présumé problème esthétique dans son ensemble.

Pour les 3 posts par semaine au milieu de la nuit où ça arrive, les utilisateurs s'en remettront

**Comment by devnewton** [comment]
wmcc a été patché

**Comment by devnewton** [comment]
Voilà c'est en prod, les aigris incapables de coder un parseur de norloge peuvent aller chercher un nouveau motif de ronchonnade!

**Comment by ckillerz** [comment]
c'est bien, tu as respecté la démocratie.

**Comment by devnewton** [comment]
En attendant les norloges ids ou les fulls norloges iso avec fraction de secondes!
