### ISSUE TITLE
Prise en charge du SVG

### ISSUE THREAD

**Issue by olibre** [devnewton/jb3#20]
L'upload d'un fichier SVG résulte en un JPEG blanc uniforme.

Exemple : https://cppfrug.org/images/Cpp-Francophonie.svg

Résultat : https://chat.cppfrug.org/pasted/b87f3196-709f-4e52-9517-164267ae6124.jpg

**Comment by devnewton** [comment]
Tu es passé par l'upload de fichier ou l'upload d'image?

**Comment by olibre** [comment]
Je cliques en bas à droite sur la trombone sur fond orange puis je sélectionne image, clique sur Parcourir... sélectionne le SVG à partir de ma mémoire de stockage locale (c'est pas un disque dur, mais un SSD). L'aperçut reste blanc, je laisse original et enfin je clique sur Upload et Attach.

**Comment by devnewton** [comment]
Ok vu.

**Comment by devnewton** [comment]
J'ai contourné le bug: pour uploader un fichier, il faut passer par le menu "file". Image sera réservé aux petits dessins/croquis.
