### ISSUE TITLE
Prise en charge du Markdown

### ISSUE THREAD

**Issue by olibre** [devnewton/jb3#21]
Le rêve que *italique* **gras** _italique_ [lien](http://cppfrug.org) s'affiche comme cela:

Le rêve que *italique* **gras** _italique_ [lien](http://cppfrug.org) s'affiche comme cela:

**Comment by devnewton** [comment]
Les balises i, b, u, s et code de html5 fonctionne.

Pour les liens, il suffit de poster l'url telle quelle, le domaine est utilisé automatiquement pour l'affichage.
