### ISSUE TITLE
Dire à Sara de se taire quand elle vient de répondre trois fois que la Journée Internationale...

### ISSUE THREAD

**Issue by olibre** [devnewton/jb3#22]
Peut être que Sara à une mémoire de poisson et qu'elle ne se rappelle plus de ce qu'elle vient de dire.
Mais si elle s'aperçoit qu'elle va donner la même réponse, vaut mieux qu'elle se taise.

**Comment by devnewton** [comment]
Sara< est stateless. Pas évident de l'éduquer au deep learning!

Un bot vraiment intelligent, ça peut être un bon projet C++  d'exemple pour le cppfrug!

**Comment by olibre** [comment]
Et si on offrait à Sara un contexte des 10 dernières questions/réponses afin de lui éviter de se répéter ?



Sinon, avoir autre chose que la Journée Internationale comme le saint et la sainte du jour....

Oh, j'ai une idée, toutes les X heures, un batch récupère les nouvelles à partir de plusieurs sites/flux comme :

- https://fr.wikipedia.org/wiki/Cat%C3%A9gorie:%C3%89v%C3%A9nement_en_cours
- https://fr.wikipedia.org/wiki/D%C3%A9c%C3%A8s_en_mai_2017
- https://fr.wikipedia.org/wiki/Mai_2017
- https://fr.wikipedia.org/wiki/29_mai
- https://fr.wikinews.org/wiki/%C3%89v%C3%A8nements_du_27_mai_2017

- http://www.agendadulibre.org/
- http://www.agendadulibre.be/
- http://www.agendadulibre.ch
- http://agendadulibre.qc.ca/

**Comment by devnewton** [comment]
sara< sera bientôt émancipée de jb3 : https://github.com/devnewton/sara
