### ISSUE TITLE
Proposer des lectures C++/Java/Python/Go/Rust/... à Sara

### ISSUE THREAD

**Issue by olibre** [devnewton/jb3#23]
Au moins, elle saurait quoi dire quand on lui demande a propos d'un langage de programmation.
Mais au fait, elle est codée avec quelle techno ?

**Comment by devnewton** [comment]
C'est un bot java intégré à jb3. Toute son intelligence est basé sur des regex et l'interrogation de webservices.

C'est pas Siri quoi :-)

**Comment by olibre** [comment]
C'est déjà balaise ce qu'elle arrive à faire juste avec des regex et quelques webservices !
Oui c'est limité... Je ne vois pas comment accroître ses connaissances...

Ah moins de recourir à un moteur de recherche qui autorise la réutilisation des résultats pour de l'IA : 
https://korben.info/wiki/les_moteurs_de_recherche_anonymes_libres_et_decentralises#moteurs_de_recherche_libres

On peut alors imaginer que sara réponde "je réflechis..." puis via un webservice de moteur de recherche + visite des pages + résumé automatique de texte... elle donne une réponse incroyable !
https://fr.wikipedia.org/wiki/R%C3%A9sum%C3%A9_automatique_de_texte

**Comment by devnewton** [comment]
Quels sites pour C++/Java/Python/Go/Rust/...?

**Comment by olibre** [comment]
Tu m'as eu... je ne sais pas trop 👅 

Mon idée était d'afficher "je réfléchi" et en même temps envoyer le *querysara* (le text après "sara<") dans un moteur de recherche, récupérer le contenu utile des pages des résultats, produire un résumé automatique, et rendre le résultat sous forme d'une synthèse (bon, faudrait pas que cela prennen 30 minutes). Attention, le texte récupéré peut être en anglais (surtout si le *querysara* est en anglais), alors là sara pourrait nous éblouir avec une traduction à la volée (euh... bof... elle risque de traduire Windows par Fenêtres et "hardcore gamer" par "dur cœur amateur de jeux vidéo" au lieu de "hyper joueur").

Bon, pour des sites francophones intéressants en réponse à ta question :

* C++
    * https://linuxfr.org/tags/c++/public
    * https://zestedesavoir.com/contenus/?tag=c%2B%2B
    * http://cppfrug.org
    * https://cpp.developpez.com/

* Java
    * https://linuxfr.org/tags/java/public
    * https://zestedesavoir.com/contenus/?tag=java
    * https://java.developpez.com/

* ...

**Comment by devnewton** [comment]
sara< sera bientôt émancipée de jb3 : https://github.com/devnewton/sara
